import turtle
turtle.shape("turtle")
square= turtle.clone()
square.shape('square')
square.penup()
square.goto(100,100)
square.goto(200,200)
square.stamp()
square.goto(100,100)
triangle=square.clone()
triangle.shape('triangle')
triangle.penup()
triangle.goto(-100,-100)
triangle.stamp()
triangle.goto(-200,-200)
